config:
  test: helloWorld!
server:
  port: 8888
sdk:
  host_ip: 192.168.10.132
  port: 8000
  token: GxSW-JKSD
  version: v0
  api:
    identify:
      threshold: 0.7
data:
  threshold: 12
  draw: 6
  thread: 1

